import type { AnalyticTask, DataProfile, ModelingRecommendation, ModelingTechnique } from '../domain/types';
const templates: Record<AnalyticTask, { technique: ModelingTechnique; fields: string[]; output: string[]; assumption: string; limitation: string; reason: string }[]> = {
  compare_categories: [{ technique: 'Descriptive aggregation', fields: ['event_id', 'source_id', 'reported_count', 'count_unit', 'count_precision'], output: ['competing_reported_counts'], assumption: 'Event IDs and units identify comparable reports.', limitation: 'Repeated observations may describe the same items; no total inventory is inferred.', reason: 'The task compares source-reported quantities.' }, { technique: 'Corroboration grouping', fields: ['event_id', 'corroboration_count'], output: ['independent_similar_reports'], assumption: 'Shared event IDs identify related reports and source independence is recorded.', limitation: 'Agreement is not verification or deduplication.', reason: 'Shows independent reports without adding their counts.' }],
  analyze_trends: [{ technique: 'Temporal trend analysis', fields: ['observed_at', 'source_id'], output: ['report_frequency', 'reporting_coverage'], assumption: 'Observation time and source coverage are recorded.', limitation: 'More reports do not establish more activity.', reason: 'The task compares report frequency and coverage over exercise time.' }, { technique: 'Rolling average', fields: ['observed_at', 'report_id'], output: ['rolling_report_frequency'], assumption: 'A stated exercise-time window is meaningful.', limitation: 'Smoothing can obscure changes in reporting coverage.', reason: 'Shows report frequency over ordered time.' }, { technique: 'Uncertainty interval display', fields: ['observed_at', 'report_id'], output: ['reported_observation_times'], assumption: 'Observation time is source-reported and distinct from receipt time.', limitation: 'A time display does not establish activity duration.', reason: 'Keeps observation timing distinct.' }],
  detect_anomalies: [{ technique: 'Z-score anomaly detection', fields: ['reported_value', 'report_time'], output: ['z_score'], assumption: 'Most observations form a useful reference distribution.', limitation: 'A z-score depends on the chosen comparison group.', reason: 'Simple deviation is inspectable.' }, { technique: 'Rolling average', fields: ['reported_value', 'report_time'], output: ['rolling_mean'], assumption: 'Local trend is informative.', limitation: 'Window length affects results.', reason: 'Provides temporal context.' }],
  examine_source_conflict: [{ technique: 'Source conflict scoring', fields: ['event_id', 'source_id', 'item_type', 'reported_count', 'count_unit', 'observed_at'], output: ['competing_reported_counts'], assumption: 'Episode grouping, item type, unit, and observation times are comparable.', limitation: 'A difference does not explain why counts differ or identify a correct report.', reason: 'The task requires report-level disagreement.' }, { technique: 'Corroboration grouping', fields: ['event_id', 'corroboration_count'], output: ['independent_similar_reports'], assumption: 'Source independence and derived-report links are explicit.', limitation: 'Similar reports do not establish unique items or truth.', reason: 'Shows similar and differing claims separately.' }],
  assess_confidence: [{ technique: 'Data-quality assessment', fields: ['source_confidence', 'validation_score', 'missingness_score'], output: ['quality_flags'], assumption: 'Each indicator has a separate meaning.', limitation: 'None of these indicators proves truth.', reason: 'Exposes distinct evidence-quality dimensions.' }, { technique: 'Uncertainty interval display', fields: ['reported_value'], output: ['uncertainty_lower', 'uncertainty_upper'], assumption: 'Model intervals describe estimated spread.', limitation: 'Synthetic intervals have no empirical calibration.', reason: 'Makes model uncertainty inspectable.' }],
  explore_provenance: [{ technique: 'Provenance tracing', fields: ['report_id', 'source_id', 'observed_at', 'received_at'], output: ['provenance_chain', 'receipt_delay_hours'], assumption: 'Recorded chain reflects generator steps and observation time is distinct from receipt time.', limitation: 'A trace records process, not truth or cause of delay.', reason: 'The task compares when reports were observed and received.' }, { technique: 'Basic clustering', fields: ['reported_count', 'observation_type'], output: ['cluster_id'], assumption: 'Comparable units are kept together.', limitation: 'Clusters are descriptive only and do not establish an inventory.', reason: 'Groups similar reported quantities for exploration.' }],
};
export function recommendModels(profile: DataProfile, task: AnalyticTask): ModelingRecommendation[] {
  const available = new Set(profile.fields.map((f) => f.name));
  return templates[task].map((item) => {
    const missing = item.fields.filter((f) => !available.has(f));
    return { technique: item.technique, reason: missing.length ? `Insufficient data: missing ${missing.join(', ')}. ${item.reason}` : item.reason, inputFields: item.fields, assumptions: [item.assumption], limitations: [item.limitation, ...(missing.length ? [`Missing fields: ${missing.join(', ')}`] : [])], outputFields: item.output, suitabilityScore: missing.length ? Math.max(0, 55 - missing.length * 20) : 92 };
  }).sort((a, b) => b.suitabilityScore - a.suitabilityScore);
}
